module-name: application-connector-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/application-connector-manager:v20240424-6e009516
  - europe-docker.pkg.dev/kyma-project/prod/central-application-gateway:v20240412-981a9bc4
  - europe-docker.pkg.dev/kyma-project/prod/central-application-connectivity-validator:v20240415-6cc5b440
  - europe-docker.pkg.dev/kyma-project/prod/compass-runtime-agent:v20240415-39507384
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
