FROM --platform=$BUILDPLATFORM golang:1.25.1-alpine3.22 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /mock-app/

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .


RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} GOFIPS140=v1.0.0 go build -v -o mock-app ./tools/external-api-mock-app

FROM scratch
COPY --from=builder /mock-app/mock-app .
ENV GODEBUG=fips140=only,tlsmlkem=0
ENTRYPOINT [ "/mock-app" ]
CMD []
