FROM --platform=$BUILDPLATFORM golang:1.25.1-alpine3.22 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /gateway-test/

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} GOFIPS140=v1.0.0 go test -v -c -o gateway-test ./test/application-gateway/

FROM scratch

COPY --from=builder /gateway-test/gateway-test /
ENV GODEBUG=fips140=only,tlsmlkem=0
ENTRYPOINT [ "/gateway-test" ]
CMD ["-test.v"]
