name: central-application-gateway-build
on:
  pull_request:
permissions:
  contents: read
jobs:
  gateway-build-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log into registry ${{ env.IMAGE_REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ secrets.GH_CR_USER }}
        password: ${{ secrets.GH_CR_PAT }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha
          type=ref,event=pr
          type=raw,value={{date 'YYYYMMDD'}}-{{sha}}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: ./components/central-application-gateway
        file: ./components/central-application-gateway
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
