name: central-application-gateway-build
on:
  pull_request:
jobs:
  gateway-build-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log into ghcr.io registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/central-application-gateway
        tags: |
          type=sha
          type=ref,event=pr
          type=raw,value={{date 'YYYYMMDD'}}-{{sha}}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: ./components/central-application-gateway
        file: ./components/central-application-gateway/Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/central-application-gateway:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/central-application-gateway:buildcache,mode=max
