name: run-cra-k3d
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  run-cra-k3d:
    # we're using reusable because we can't modify workflows as contributors
    # it could cause the secret leakeages
    uses: "./.github/workflows/reusable-k3d-agent-test.yml"
    with:
      k3d-version: v5.4.6
    secrets:
      compass-host: ${{ secrets.COMPASS_HOST }}
      compass-client-id: ${{ secrets.COMPASS_CLIENT_ID }}
      compass-client-secret: ${{ secrets.COMPASS_CLIENT_SECRET }}
