name: Run compass-runtime-agent integration tests on k3d
on:
  workflow_call:
    inputs:
      k3d-version:
        required: true
        type: string
        default: v5.6.0
    secrets:
      compass-host:
        required: true
      compass-client-id:
        required: true
      compass-client-secret:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-helm@v4.1.0
        id: install-helm
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.1
      - name: install-k3d
        env:
          K3D_URL: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
          DEFAULT_K3D_VERSION: ${{ inputs.k3d-version }}
        run: curl --silent --fail $K3D_URL | TAG=$DEFAULT_K3D_VERSION bash
      - name: run-tests
        env:
          COMPASS_CLIENT_ID: ${{ secrets.compass-client-id }}
          COMPASS_CLIENT_SECRET: ${{ secrets.compass-client-secret }}
          COMPASS_HOST: ${{ secrets.compass-host }}
        run: make -C tests/hack/ci k3d-agent-tests
      - name: archive-logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k3d-agent-test-logs
          path: compass-runtime-agent-test.log
      - name: test summary
        run: |
          {
            echo "# K3D Agent Test Summary:"
            echo "<details>"
            echo "<summary>Click to expand logs</summary>"
            printf '\n```\n'
            cat compass-runtime-agent-test.log
            printf '\n```\n'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
